Feat/rate limiter test
ContentSquare/chproxy pull request #15
Opened 2021-11-15 15:59 UTC by JingmaoYou

The test file for sliding_log algo

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	shaLua, err := slrl.client.ScriptLoad(slrl.client.Context(), luaScript).Result()
you shouldn't load the script at every call to `Limit`. `Limit` method should only evaluate script with given parameters. Can you move it to factory method?

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	nowTimeStamp := time.Now().UnixNano()
Without knowing the constraints we have that made us chose solution with explicit value of unix timestamp, future developers wouldn't understand the reason of existence of `nowTimeStamp`. I suggest we extract it as a private method with meaningful name

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	values := []interface{}{int64(60), rlk.Limit, nowTimeStamp}
We should use the window value provided in `RateLimitKey `. 
For that you'll need to create a mapping from regarded `Duration` to equivalent amount in seconds due to the fact that sorted set's score is a timestamp in seconds.

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/rate_limiter.go
> +func PerService(key string, limit uint32) RateLimitKey {
What's the rational behind calling it `PerService` ?

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	rlk := PerService("testKey", 0)
we should not allow `RateLimitKey` to have a limit = 0

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	vals, err := slrl.client.EvalSha(slrl.client.Context(), shaLua, keys, values...).Int()
`vals` does not represent well the variable. How would you call it alternatively?

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	rlk := PerService("testKey", 0)
it makes me think that with current implementation we allow 1 request to pass, whereas the limit is 0. That's unintentional isn't it?

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	time.Sleep(60*time.Second - time.Since(start))
that will slow down tests immensely. We should change it after fixing hardcoded `window` in sliding_log implementation

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	time.Sleep(60*time.Second - time.Since(start))
Also, from this point onwards we have a 2nd test case. Let's create a dedicated test for that :)

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	for i := 0; i < len(vals); i++ {
not sure what value it brings. What is the rational behind it?

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +func TestLimit(t *testing.T) {
we miss validation of `ttl` set on the key

2021-11-16 08:53 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +const luaScript = `local pgname = KEYS[1]
why `pgname` ?

2021-11-16 15:33 UTC, JingmaoYou commented on services/ratelimiter/slide_log.go
> +const luaScript = `local pgname = KEYS[1]
change it to "member"

2021-11-16 15:36 UTC, JingmaoYou commented on services/ratelimiter/slide_log_test.go
> +	rlk := PerService("testKey", 0)
Yes, this is because of the logic of the script. I change the lua script to if amount < limit to fix the problem.

2021-11-16 15:37 UTC, JingmaoYou commented on services/ratelimiter/rate_limiter.go
> +func PerService(key string, limit uint32) RateLimitKey {
I thought this is the limit for every service, I could just give it a general name for now: NewRateLimitKey()

2021-11-16 15:39 UTC, JingmaoYou commented on services/ratelimiter/slide_log.go
> +	nowTimeStamp := time.Now().UnixNano()
Add a private function: generateRedisMember()

2021-11-16 16:22 UTC, JingmaoYou commented on services/ratelimiter/slide_log_test.go
> +	time.Sleep(60*time.Second - time.Since(start))
Done

2021-11-17 08:26 UTC, Garnek20 commented on services/ratelimiter/rate_limiter.go
> +func PerService(key string, limit uint32) RateLimitKey {
Given that the fields of this `struct` are public I don't see the advantage of adding dedicated `NewRateLimitKey`

2021-11-17 13:48 UTC, Garnek20 requested changes

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +type SlidingLogRateLimiter struct {
We can actually make it private as it's an implementation detail of `RateLimiter` interface

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +const LuaScript = `local key = KEYS[1]
it should be private to the package as well. No one else but the implementation of rate limiter should be able to use the script

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	window := int64(rlk.Window / time.Second)
Coool!

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +		return false, fmt.Errorf("the evalsha failed: %w", err)
`the evalsha failed` is an implementation detail that we don't need to leak, because how clients could understand it? 
I'd suggest we call it : `failed to evaluate limit for key: %s: %w`

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	rest, err := slrl.client.EvalSha(slrl.client.Context(), slrl.shaLuaScript, key, values...).Int()
```suggestion
	remaining, err := slrl.client.EvalSha(slrl.client.Context(), slrl.shaLuaScript, key, values...).Int()
```

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	if rest < 0 {
we should have here following condition instead:
```
if remaining == 0
```

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +func NewSlidingLogRateLimiter(client redis.UniversalClient, luaScript string) (*SlidingLogRateLimiter, error) {
I don't think you should take lua script as an argument. What's the motivation?

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/rate_limiter.go
> +func NewRateLimitKey(key string, limit uint32) RateLimitKey {
In golang, there's a convention to call factory methods returning pointers with `New*` and returning references with `Make*`. Regardless, I think that we don't need this factory actually. We will create ratelimit key with window specified by the user of API

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	s, err := miniredis.Run()
this is repeated in each test. We could create it only once at the beginning of execution of each test within this file. For that golang standard testing library uses `TestMain` , you can refer to https://medium.com/goingogo/why-use-testmain-for-testing-in-go-dafb52b406bc

It'd be great if you took an inspiration from the article to extract it into logical block called `Setup` and invoke at the beginning of all the tests. 🙂

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +		Window: 10 * time.Second,
Can we test it instead for a duration of one second?

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	if res != true {
This is wrong. We should not limit the key because it's the first call to limit and defined rate limit is 1

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +func TestLimit(t *testing.T) {
Can you call it`TestLimitExceed` ?

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +package ratelimiter
we miss test for sliding window scenario. Therefore `TestLimitSlidingWindow`

2021-11-17 13:48 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +		panic(err)
instead of panicking, you should use error reporting from testing framework. `t.Fatal()`

2021-11-17 15:40 UTC, Garnek20 commented
Once you tackle all the above comments, we need one more test scenario
- concurrently (by spawning multiple go routines) evaluate limitation preservation. This way we'll test race conditions and check how rate limiter in case of a rapid growth of traffic

2021-11-18 08:45 UTC, JingmaoYou commented on services/ratelimiter/slide_log_test.go
> +	for i := 0; i < len(vals); i++ {
I use this way to check the data in the redis, make sure that the number of values in redis is as expected. I delete this one, maybe this could be a separate test.

2021-11-18 08:45 UTC, JingmaoYou commented on services/ratelimiter/slide_log_test.go
> +func TestLimit(t *testing.T) {
Done

2021-11-18 10:07 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	shaLuaScript, err := client.ScriptLoad(client.Context(), luaScript).Result()
Anytime we interact with external dependency, such as: database, another service etc we should establish a timeout on the operation. The reason for that are:
-  faulty network. We can loose packets or it can just take ages to arrive from EU to Singapore 
- third party errors

Could you add timeouts to operations on `redis`?

2021-11-18 13:01 UTC, JingmaoYou commented on services/ratelimiter/slide_log_test.go
> +	if res != true {
discussed offline. solved

2021-11-18 16:00 UTC, JingmaoYou commented on services/ratelimiter/slide_log_test.go
> +		panic(err)
use os.Exit(1) in the testmain, since testing.m does not have the fatal

2021-11-19 08:34 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	//judge the 0 here
we can remove this comment 🙂

2021-11-19 08:34 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +type slidingLogRateLimiter struct {
in the following PR it'd be also nice to thoroughly document it

2021-11-19 08:35 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +func generateRedisMember() int64 {
can we call it `generateSortedSetMember` ?

2021-11-19 08:39 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +func Reset() {
It's more like `Shutdown()` :)

2021-11-19 08:46 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +		return true, nil
I just realised that this is the opposite of what we want. Looking at the signature `Limit() (bool, error)` , we'd rather expect the meaning of return boolean to be true when we need to throttle the request. Therefore, in this line we don't want to limit yet (false), while in the line 67 we do (true). Do you agree?

2021-11-19 08:49 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +var err error
I understand why you need this variable. You want to assign output of `miniredis.Run()` to variables, otherwise it's not the case. Can you put it into the scope of `Setup` function at least?

2021-11-19 08:50 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +
we should have one more call to `Limit` and validate that it's limit is exceeded.

2021-11-19 08:50 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	time.Sleep(1*time.Second + 500*time.Millisecond)
Can you also document why do we await 1.5 sec ?

2021-11-19 09:43 UTC, JingmaoYou commented on services/ratelimiter/slide_log.go
> +		return true, nil
I think you are right. Just one thing: the remaining could only be ==0 or > 0. So the logic here could be: if the remaining == 0, return true, we need to throttle the request. Else, if the remaining >0, the return is false.

2021-11-19 13:06 UTC, Garnek20 approved these changes
LGTM 💯

2021-11-19 13:12 UTC, merged