Feat/rate limiter goroutine
ContentSquare/chproxy pull request #17
Opened 2021-11-22 10:35 UTC by JingmaoYou

add new goroutine test, add context, pass the new test and ready for review

2021-11-22 13:16 UTC, Garnek20 commented on go.mod
> +	golang.org/x/sync v0.0.0-20201020160332-67f06af15bc9
we don't need that. Let's remove it

2021-11-24 09:44 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	1. Method: Implement the Limit method, if the rate reaches the limit, it will return true, else it will return false.
This comment is more appropriate to be at the `Limit` method and then you don't need to explain to what it refers. 
Also, your comment is very generic whereas we're in the implementation of the interface. It's worth to say how limit is performed.

Worth mentioned that limit is expected to be >0

2021-11-24 09:45 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	2. Trade-off: We choose to use redis to store the timestamp, instead of using memory. The usage of redis could make the storage more stable, but it might cost some time due to the communication with
I don't understand this comment. What do you mean?

2021-11-24 09:48 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	For each new coming query, the script gets the timestamp from redis as the score, get the timestamp from golang as the member. It gets the window size and limit from the arguments. It cleans all the
This is the part worth noting on top of the struct definition. However I believe you go in too much details and as a result it might be confusing

2021-11-24 09:50 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	4. Data structure: The data structure includes a redis universal client and a string. The client is used to communicate with redis, and the string is used to store the SHA of the lua script.
I think there's no value in this comment

2021-11-24 09:58 UTC, Garnek20 requested changes
Please rebase your branch ;)

2021-11-24 09:58 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	time.Sleep(1 * time.Second)
This is not desired. We should avoid relying on time in those scenarios. What you need here is to await completion of all launched go routines. You can achieve that by using `waitgroup` https://gobyexample.com/waitgroups

2021-11-24 09:58 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	for i := 0; i < len(results); i++ {
you can simplify it, any idea how?

2021-11-24 14:25 UTC, JingmaoYou commented on services/ratelimiter/slide_log.go
> +	2. Trade-off: We choose to use redis to store the timestamp, instead of using memory. The usage of redis could make the storage more stable, but it might cost some time due to the communication with
I am not really clear about the trade-off here. For now, we keep the timestamp in the Redis database, if we keep all the timestamps in the memory, we might be able to save some time.

2021-11-24 14:27 UTC, JingmaoYou commented on services/ratelimiter/slide_log.go
> +	1. Method: Implement the Limit method, if the rate reaches the limit, it will return true, else it will return false.
Method: The Limit method decides whether the current rate of incoming queries is above the limit rate. If the current rate is too high, it will return true, meaning the rate reaches the limit, else it will return false.
For every new coming query, the method will calculate a timestamp for it and try to insert it into the Redis database.
The method uses the limit parameter in RateLimitKey(> 0) and the number of timestamps in the [current_time - window_duration, current_time] to calculate how many timestamps could be added into the Redis database. If the remaining number is larger than 0, it will insert a new timestamp and return false, else it will not insert the timestamp and return true.

2021-11-24 16:01 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	2. Trade-off: We choose to use redis to store the timestamp, instead of using memory. The usage of redis could make the storage more stable, but it might cost some time due to the communication with
If we used in memory representation, we wouldn't be able to control well the traffic if we deployed many replicas of `chproxy`. You can skip this description, just mention somewhere that we chose to supply members as unix timestamps to populate random sorted sot members - sorted set, because it's a set, does not allow duplicates.

2021-11-24 16:03 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +	1. Method: Implement the Limit method, if the rate reaches the limit, it will return true, else it will return false.
You should follow golang convention to documentation https://go.dev/doc/effective_go#commentary (when you document a method ). Provide your proposition in the next commit and we'll iterate :)

2021-11-24 16:25 UTC, JingmaoYou commented on services/ratelimiter/slide_log.go
> +	For each new coming query, the script gets the timestamp from redis as the score, get the timestamp from golang as the member. It gets the window size and limit from the arguments. It cleans all the
Algorithm: the universal client is used to communicate with Redis database. The shaLuascript is used to store the SHA value of the Lua script. The main logic is written in the Lua script. Once the script is called, we will try to create a member insert it into the Redis sorted set. 
The sorted set is a data structure, each member in the sorted set is unique, and each member is associated with a score. The member has to be unique and we need to consider the situation when there are multiple Limit calls in one second, so we use the UNIX time in Golang. The score does not need to be unique, and we need to make sure that multiple instances of applications' clocks are synchronized, so we choose to use the TIME in redis, the UNIX time in second.

2021-11-24 16:30 UTC, JingmaoYou commented on services/ratelimiter/slide_log.go
> +	For each new coming query, the script gets the timestamp from redis as the score, get the timestamp from golang as the member. It gets the window size and limit from the arguments. It cleans all the
I will consult the golang convention of documentation and renew it. Just skip this comment for now.

2021-11-24 17:16 UTC, JingmaoYou commented on services/ratelimiter/slide_log_test.go
> +	time.Sleep(1 * time.Second)
Yes, but we still need to use the sync wait group.

2021-11-24 17:39 UTC, JingmaoYou commented on services/ratelimiter/slide_log_test.go
> +	time.Sleep(1 * time.Second)
Done

2021-11-24 17:40 UTC, JingmaoYou commented on services/ratelimiter/slide_log_test.go
> +	for i := 0; i < len(results); i++ {
Done

2021-11-25 15:12 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +// shaLuaScript is used to store the SHA value of the lus script.
```suggestion
// slidingLogRateLimiter using sorted set implements a `sliding log window` algorithm. Algorithm is implemented with lua script uploaded at the creation of the limiter and referred to via hash [[shaLuaScript]].
```

2021-11-25 15:14 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +// Limit method decides whether the current rate of incoming queries is above the limit rate.
```suggestion
// Limit decides whether the current rate of provided key [[rlk]] is above the limit rate.
```

2021-11-25 15:15 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +// If the current rate is too high, it will return true, meaning the rate reaches the limit, else it will return false.
```suggestion
// If the rate is too high, it will return true signalling exceeded limit. Otherwise it will return false.
```

2021-11-25 15:16 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +// If the remaining number is larger than 0, it will insert a new timestamp and return false, else it will not insert the timestamp and return true.
I think we don't need it here given we explain on top of lua script the algorithm

2021-11-25 15:22 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +// The sorted set is accessed through the key.
```suggestion
// luaScript is used to implement a sliding log in order to optimise amount of roundtrips to Redis.
// Algorithm relies on a sorted set data structure in which every member is unique and has associated timestamp as a score.
// We decided to feed member value from application because we can't rely on a timestamp provided by redis. It gives as a value in seconds. Because we can have multiple calls per second we would end up with incorrect state of data. 
// We use Redis' timestamp to have the same clock reference across multiple replicas of chproxy.
```

2021-11-25 15:22 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +// The sorted set is accessed through the key.
We miss information about how algorithm performs sliding window. Could you suggest doc about it?

2021-11-25 15:24 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	for i := 0; i < len(results); i++ {
It's still not completely satisfying. Do we need to keep track of every result in a separate slice? At the end what we're interested in is amount of `reached limits` . Can't we just use the counter?

2021-11-25 15:25 UTC, JingmaoYou commented on services/ratelimiter/slide_log.go
> +// The sorted set is accessed through the key.
I tried to provide this information above the Limit method. Explain the algorithm of the sliding window.

2021-11-25 15:27 UTC, Garnek20 commented on services/ratelimiter/slide_log.go
> +// The sorted set is accessed through the key.
However, since you explained so thoroughly script it might be a good idea to include algo information at this point

2021-11-26 15:59 UTC, Garnek20 commented on services/ratelimiter/slide_log_test.go
> +	for i := 0; i < len(results); i++ {
What about this? @JingmaoYou

2021-11-26 16:18 UTC, Garnek20 approved these changes
LGTM ✅

2021-11-29 07:45 UTC, merged