fix(asyncCache): propagation of maxExecutionTime
ContentSquare/chproxy pull request #190
Opened 2022-07-15 14:43 UTC by Garnek20

## Description
Fix propagation of **max_execution_time** to async cache.
  
 

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Checklist

- [x] Linter passes correctly
- [ ] Add tests which fail without the change (if possible)
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Further comments

2022-07-18 09:31 UTC, mga-chka requested changes

2022-07-18 09:31 UTC, mga-chka commented on proxy.go
>  				maxExecutionTime = user.MaxExecutionTime
what if multiple users have the same cache but different max execution time?
IHMO we should have "one cache per user" because this single cache breaks a bit the logic of CHProxy.
But for the short term solution, we should at least take the max of all the maxExecutionTime, wdyt?

2022-08-11 16:36 UTC, Garnek20 commented on proxy.go
>  				maxExecutionTime = user.MaxExecutionTime
Sounds good. I'll prepare the fix

2022-08-11 17:12 UTC, mga-chka approved these changes

2022-08-11 17:19 UTC, merged